services:
  saporive-db:
    image: postgres:15-alpine
    container_name: saporive-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Soporte*"
      POSTGRES_DB: saporiDB
    ports:
      - "5432:5432"
    volumes:
      - saporive_data:/var/lib/postgresql/data

  saporive-api:
    build: .
    container_name: saporive-api-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - saporive-db

volumes:
  saporive_data: